### ISSUE TITLE
Add nitro from nuxt

### ISSUE THREAD

**Issue by oom-** [Vanilla-IceCream/fastify-uws#2]
Hello, could you add nitro from nuxt in your results please ? I suppose it will be a little below h3.

Thanks.

**Comment by Shyam-Chen** [comment]
My primary benchmarking focus is on the web server performance of the framework.

- hyper
  - warp
  - axum
  - graphul
  - poem
- bun
  - elysia
  - hono
  - h3
  - oak
- uws
  - hyper-express
  - fastify-uws
- deno
  - nhttp
  - hono
  - oak
- node
  - polka
  - fastify
  - hono
  - h3
    - nitro <- Adding `nitro` will place it here
      - nuxt <- Adding `nuxt` will place it here
  - express

---

But in reality, there are only three underlying web servers. 

- hyper
  - deno
- uws
  - bun
- node
